# -*- coding: utf-8 -*-
"""
Documentation config file
"""
#
# Configuration file for the Sphinx documentation builder.
#
# This file does only contain a selection of the most common options. For a
# full list see the documentation:
# http://www.sphinx-doc.org/en/stable/config

# -- Path setup --------------------------------------------------------------

# If extensions (or modules to document with autodoc) are in another directory,
# add these directories to sys.path here. If the directory is relative to the
# documentation root, use os.path.abspath to make it absolute, like shown here.
#
import os
import sys
import sphinx_rtd_theme
from sphinx.ext.autodoc import between
sys.path.insert(0, os.path.abspath('../../'))

# -- Project information -----------------------------------------------------

project = 'reVX'
copyright = '2026, Alliance for Energy Innovation, LLC'
author = 'NLR: Michael Rossol, Grant Buster, Paul Pinchuk'

pkg = os.path.dirname(os.path.abspath(os.path.dirname(__file__)))
pkg = os.path.dirname(pkg)
sys.path.append(pkg)

from reVX.version import __version__ as v
# The short X.Y version
version = v
# The full version, including alpha/beta/rc tags
release = v

# -- General configuration ---------------------------------------------------

# If your documentation needs a minimal Sphinx version, state it here.
#
# needs_sphinx = '1.0'

# Add any Sphinx extension module names here, as strings. They can be
# extensions coming with Sphinx (named 'sphinx.ext.*') or your custom
# ones.
extensions = [
    "sphinx.ext.autodoc",
    "sphinx.ext.autosummary",
    "sphinx.ext.doctest",
    "sphinx.ext.intersphinx",
    "sphinx.ext.coverage",
    "sphinx.ext.mathjax",
    "sphinx.ext.viewcode",
    "sphinx.ext.githubpages",
    "sphinx.ext.napoleon",
    "sphinx_rtd_theme",
    'sphinx_click.ext',
    "sphinx_tabs.tabs",
    "sphinx_copybutton",
    "myst_parser",
]

intersphinx_mapping = {
    "python": ("https://docs.python.org/3/", None),
    "affine": ("https://affine.readthedocs.io/en/latest/", None),
    "cartopy": ("https://cartopy.readthedocs.io/stable/", None),
    "dask": ("https://docs.dask.org/en/latest/", None),
    "distributed": ("https://distributed.dask.org/en/stable/", None),
    "elm": ("https://natlabrockies.github.io/elm", None),
    "gaps": ("https://natlabrockies.github.io/gaps/", None),
    "geopandas": ("https://geopandas.org/en/stable/", None),
    "geoplot": ("https://residentmario.github.io/geoplot", None),
    "matplotlib": ("https://matplotlib.org/stable", None),
    "networkx": ("https://networkx.org/documentation/stable", None),
    "numpy": ("https://numpy.org/doc/stable/", None),
    "odc-geo": ("https://odc-geo.readthedocs.io/en/latest/", None),
    "pandas": ("https://pandas.pydata.org/pandas-docs/stable", None),
    "plotly": ("https://plotly.com/python-api-reference", None),
    "psycopg": ("https://www.psycopg.org/psycopg3/docs", None),
    "pyproj": ("https://pyproj4.github.io/pyproj/stable/", None),
    'PySAM': ('https://nrel-pysam.readthedocs.io/en/latest/', None),
    "rasterio": ("https://rasterio.readthedocs.io/en/stable/", None),
    'rex': ('https://natlabrockies.github.io/rex/', None),
    'reV': ('https://natlabrockies.github.io/reV/', None),
    "rioxarray": ("https://corteva.github.io/rioxarray/stable/", None),
    "shapely": ("https://shapely.readthedocs.io/en/stable/", None),
    "sqlalchemy": ("https://docs.sqlalchemy.org/en/20/", None),
    "xarray": ("https://docs.xarray.dev/en/stable/", None),
}

# Add any paths that contain templates here, relative to this directory.
templates_path = ['_templates']

# The suffix(es) of source filenames.
# You can specify multiple suffix as a list of string:
#
source_suffix = '.rst'

# source_parsers = {'.md': MarkdownParser}

# The master toctree document.
master_doc = 'index'

# The language for content autogenerated by Sphinx. Refer to documentation
# for a list of supported languages.
#
# This is also used if you do content translation via gettext catalogs.
# Usually you set "language" from the command line for these cases.
language = "en"

# List of patterns, relative to source directory, that match files and
# directories to ignore when looking for source files.
# This pattern also affects html_static_path and html_extra_path .
exclude_patterns = [
    "**.ipynb_checkpoints",
    "**__pycache__**",
    # to ensure that include files (partial pages) aren't built, exclude them
    # https://github.com/sphinx-doc/sphinx/issues/1965#issuecomment-124732907
    "**/includes/**",
]

# The name of the Pygments (syntax highlighting) style to use.
pygments_style = 'sphinx'

# Avoid errors with self-signed certificates
tls_verify = False

# Avoid warning about api.rst not in TOC
suppress_warnings = ["toc.not_included"]

# -- Options for HTML output -------------------------------------------------

# The theme to use for HTML and HTML Help pages.  See the documentation for
# a list of builtin themes.
#
html_theme = 'sphinx_rtd_theme'

# Theme options are theme-specific and customize the look and feel of a theme
# further.  For a list of options available for each theme, see the
# documentation.
#
html_theme_options = {"navigation_depth": 4, "collapse_navigation": False}
html_css_file = ["custom.css"]

html_context = {
    "display_github": True,
    "github_user": "NatLabRockies",
    "github_repo": "reVX",
    "github_version": "main",
    "conf_py_path": "/docs/source/",
    "source_suffix": source_suffix,
}

# Add any paths that contain custom static files (such as style sheets) here,
# relative to this directory. They are copied after the builtin static files,
# so a file named "default.css" will overwrite the builtin "default.css".
html_static_path = ['_static']

# Custom sidebar templates, must be a dictionary that maps document names
# to template names.
#
# The default sidebars (for documents that don't match any pattern) are
# defined by theme itself.  Builtin themes are using these templates by
# default: ``['localtoc.html', 'relations.html', 'sourcelink.html',
# 'searchbox.html']``.
#
# html_sidebars = {}


# -- Options for HTMLHelp output ---------------------------------------------

# Output file base name for HTML help builder.
htmlhelp_basename = 'reVXdoc'

# -- Options for LaTeX output ------------------------------------------------

latex_elements = {
    # The paper size ('letterpaper' or 'a4paper').
    #
    # 'papersize': 'letterpaper',

    # The font size ('10pt', '11pt' or '12pt').
    #
    # 'pointsize': '10pt',

    # Additional stuff for the LaTeX preamble.
    #
    # 'preamble': '',

    # Latex figure (float) alignment
    #
    # 'figure_align': 'htbp',
}

# Grouping the document tree into LaTeX files. List of tuples
# (source start file, target name, title,
#  author, documentclass [howto, manual, or own class]).
latex_documents = [
    (master_doc, 'reVX.tex', 'reVX Documentation',
     'Michael Rossol, Grant Buster', 'Paul Pinchuk', 'manual'),
]

# -- Options for manual page output ------------------------------------------

# One entry per manual page. List of tuples
# (source start file, name, description, authors, manual section).
man_pages = [
    (master_doc, 'reVX', 'reVX Documentation',
     [author], 1)
]

# -- Options for Texinfo output ----------------------------------------------

# Grouping the document tree into Texinfo files. List of tuples
# (source start file, target name, title, author,
#  dir menu entry, description, category)
texinfo_documents = [
    (master_doc, 'reVX', 'reVX Documentation',
     author, 'reVX', 'One line description of project.',
     'Miscellaneous'),
]

def skip_external_methods(name, obj):
    obj_module = getattr(obj, "__module__", "")
    property_module = getattr(getattr(obj, "fget", None), "__module__", "")

    if name == "model_config":
        return True

    if name.startswith("model_") and (
        obj_module.startswith("pydantic")
        or property_module.startswith("pydantic")
    ):
        return True

    mapping_methods = {
        "clear",
        "pop",
        "popitem",
        "setdefault",
        "update",
    }

    if name in mapping_methods and (
        "MutableMapping" in str(obj)
        or "TypedDict" in str(obj)
        or getattr(obj, "__doc__", "").startswith("D.")
    ):
        return True

    if name in {"copy", "fromkeys"} and "TransmissionConfig" in str(obj):
        return True

    if name in {"items", "keys", "values"} and "Mapping" in str(obj):
        return True

    if name in {"copy", "get"} and "UserDict" in str(obj):
        return True

    if name in {
        "model_dump_json",
        "model_json_schema",
        "model_dump",
        "model_construct",
        "model_copy",
        "model_config",
        "model_fields",
        "model_computed_fields",
        "model_rebuild",
        "model_parametrized_name",
        "model_post_init",
        "model_validate",
        "model_validate_json",
        "model_validate_strings",
        "copy",
        "construct",
        "dict",
        "from_orm",
        "json",
        "parse_file",
        "parse_obj",
        "parse_raw",
        "schema",
        "schema_json",
        "update_forward_refs",
        "validate",
    } and "BaseModel" in str(obj):
        return True

    return None


def _skip_internal_api(obj):
    return (getattr(obj, "__doc__", None) or "").startswith("[NOT PUBLIC API]")


def _skip_member(app, what, name, obj, skip, options):
    if _skip_internal_api(obj) or skip_external_methods(name, obj):
        return True
    return None


def setup(app):
    app.connect("autodoc-skip-member", _skip_member)

    # Register a sphinx.ext.autodoc.between listener to ignore everything
    # between lines that contain the word IGNORE
    app.connect(
        "autodoc-process-docstring", between("^.*IGNORE.*$", exclude=True)
    )
    return app

# -- Extension configuration -------------------------------------------------

autosummary_generate = True  # Turn on sphinx.ext.autosummary
autoclass_content = "both"  # Add __init__ doc (ie. params) to class summaries
autodoc_member_order = 'bysource'
autodoc_inherit_docstrings = True  # If no docstring, inherit from base class
add_module_names = False  # Remove namespaces from class/method signatures
# Remove 'view source code' from top of page (for html, not python)
html_show_sourcelink = False
numpy_show_class_member = True
napoleon_google_docstring = False
napoleon_use_param = False
napoleon_use_ivar = False
napoleon_use_rtype = False
